### PR TITLE
Add warning when exiting import page early

### PR DESCRIPTION
**Pull request by AbdiTolesa**
Fix https://github.com/Strategy11/formidable-locations/issues/12
CleanShot 2024-08-20 at 20 25 44

### CODE REVIEW

**Comment by Crabcyborg** [comment]
Thanks @AbdiTolesa.

Can we also add the visible note to the page like we have for our import? This way the users understand why the pop up is happening?

Screen Shot 2024-08-21 at 10 43 17 AM

**Comment by Crabcyborg** [comment]
@AbdiTolesa It also looks like the workflows are failing. Unrelated to your current updates, so it might be better to solve this in a separate PR, but could you help with getting them passing again?

Thank you!

**Comment by AbdiTolesa** [comment]
> @AbdiTolesa It also looks like the workflows are failing. Unrelated to your current updates, so it might be better to solve this in a separate PR, but could you help with getting them passing again?
> 
> Thank you!

@Crabcyborg Sure, I have make the workflows pass in a separate PR: https://github.com/Strategy11/formidable-locations/pull/18

**Comment by AbdiTolesa** [comment]
> Can we also add the visible note to the page like we have for our import? This way the users understand why the pop up is happening?

This is done too.

**Review by Crabcyborg — APPROVED** [review]
Thank you @AbdiTolesa!

I think this is good to merge now.🚀

**Pull request merged**
