### PR TITLE
Remove deprecations, fix import, add comments and fix spacing, add workflows

### PR DESCRIPTION
**Pull request by Crabcyborg**
- Also fixes https://github.com/Strategy11/formidable-locations/issues/7
- Fixes https://github.com/Strategy11/formidable-locations/issues/6 which is a result of this update https://github.com/Strategy11/formidable-locations/commit/28b37d56c25af95dda3c76518b06aecf9e13cb08 where 9 entries were removed.
- The states count was also updated as it wasn't accurate.
- Adds PHPStan, Psalm, and PHPCS configurations and workflows.
- Fixes spacing, adds type comments, validates types more.
- Adding additional content escaping.

There's also an issue with importing the "US Tax Department" "city" with a "1920" state value. That's fixed separately in https://github.com/Strategy11/formidable-locations/pull/9 and I merged it into this branch now, so it should work as well here.

### CODE REVIEW

**Comment by garretlaxton** [comment]
My locations lookup fields are blank still after the import. I can see they are added in the list form though.
image

**Comment by Crabcyborg** [comment]
@garretlaxton I believe the lookup requires changes to properly set up. If you only import cities, it works for me if I delete the country dropdown, then update the state dropdown so it isn't watching the country dropdown. If it starts with the list of all states, the counties and cities all work from there for me.

**Review by garretlaxton — APPROVED** [review]
Ahh, thanks. I only imported the US States one, which is why it wasn't pulling up the information.

**Review by stephywells — APPROVED** [review]
This looks great! Nice update

**Pull request merged**
